query getProjects($a: String){
  query getProjects(a: $a){
    thumbnail
    links {
      url
      label
      description
    }
    introspeccion{
      languages {
        label
        icon
      }
    }
  }
}

